100-hours-a-week/18-team-timeline-ai

- scrapers/serper.py
> serper.py 1차

- api/hot.py
- api/router.py
- main.py
- scrapers/serpapi.py
- scrapers/serper.py
> main.py, router.py

- api/hot.py
- api/router.py
- main.py
- models/response_schema.py
- models/timeline_card.py
> 라우팅 코드, 객체 설정

- api/hot.py
- api/merge.py
- api/timeline.py
- scrapers/serper.py
- utils/timeline_utils.py
Feature/james 엔드포인트 구현 (Timeline, Merge)
> Feature/james 엔드포인트 구현 (Timeline, Merge)

- api/merge.py
- api/timeline.py
- scrapers/serper.py
> 엔드포인트 디버깅, 동작 확인

- api/comment.py
- api/hot.py
- api/merge.py
- api/timeline.py
> Feature/james (댓글 개수, 에러 리턴 처리)

- ai_models/graph/classify.py
- api/comment.py
- scrapers/daum_vclip_searcher.py
- test_comment.py
> Feature/james (댓글 분류 시 검색어 넣기)

- ai_models/graph/classify.py
- test_comment.py
> Feature/cole(1차 배포)

- api/timeline.py
> 4096 토큰에 맞게 기사 자르기

- ai_models/runner.py
- api/comment.py
- api/merge.py
- api/timeline.py
- scrapers/filter.py
- utils/env_utils.py
> Feature/james (무의미한 검색어 필터링 + Runner 롤백)

- api/timeline.py
- main.py
- models/timeline_card.py
- scrapers/serper.py
> Feature/james (SlowAPI Rate Limit)

- api/timeline.py
> slowAPI 문법 오류 수정

- pyproject.toml
> slowAPI requirement 명시

- api/timeline.py
SlowAPI 수정 (limiter from main)
> SlowAPI 수정 (limiter from main)

- api/timeline.py
- limiter.py
- main.py
> SlowAPI 수정 (limiter.py로 분리)

- main.py
> SlowAPI 수정 (starlette)

- api/timeline.py
> SlowAPI 수정 (Request 변수명)

- api/merge.py
- api/timeline.py
> 리턴 시 날짜를 date isoformat으로

- api/timeline.py
> date isoformat 재수정

- api/merge.py
> merge date isoformat 재수정

- api/merge.py
- api/timeline.py
- utils/env_utils.py
- utils/timeline_utils.py
Multi API KEY + Compress sentence
> Feature/james (Multi API KEY + Compress sentence)

- api/comment.py
- api/merge.py
- api/timeline.py
> Feature/james (엔드포인트에서 LangChain 제거)

- ai_models/host.py
- ai_models/manager.py
- ai_models/pipeline.py
- api/comment.py
- api/timeline.py
- classify/sentiment.py
- classify/storage.py
- pyproject.toml
- scrapers/serper.py
> Feature/james (뉴스 중복 방지)

- ai_models/pipeline.py
- api/timeline.py
- classify/cluster.py
- main.py
- 뉴스 태그 클러스터링 (K-Means)
- LLM 프롬프팅을 이용한 태그 폐기
> Feature/james (뉴스 태그 클러스터링)
